// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: ds_api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ds_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_ds_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_ds_api_proto_rawDescGZIP(), []int{0}
}

type ServerTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *ServerTime) Reset() {
	*x = ServerTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ds_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTime) ProtoMessage() {}

func (x *ServerTime) ProtoReflect() protoreflect.Message {
	mi := &file_ds_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTime.ProtoReflect.Descriptor instead.
func (*ServerTime) Descriptor() ([]byte, []int) {
	return file_ds_api_proto_rawDescGZIP(), []int{1}
}

func (x *ServerTime) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type KlinesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol   string `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Interval string `protobuf:"bytes,2,opt,name=Interval,proto3" json:"Interval,omitempty"`
	Limit    int32  `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
}

func (x *KlinesRequest) Reset() {
	*x = KlinesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ds_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KlinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KlinesRequest) ProtoMessage() {}

func (x *KlinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ds_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KlinesRequest.ProtoReflect.Descriptor instead.
func (*KlinesRequest) Descriptor() ([]byte, []int) {
	return file_ds_api_proto_rawDescGZIP(), []int{2}
}

func (x *KlinesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *KlinesRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *KlinesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type KlinesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Klines []string `protobuf:"bytes,1,rep,name=Klines,proto3" json:"Klines,omitempty"`
}

func (x *KlinesResponse) Reset() {
	*x = KlinesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ds_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KlinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KlinesResponse) ProtoMessage() {}

func (x *KlinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ds_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KlinesResponse.ProtoReflect.Descriptor instead.
func (*KlinesResponse) Descriptor() ([]byte, []int) {
	return file_ds_api_proto_rawDescGZIP(), []int{3}
}

func (x *KlinesResponse) GetKlines() []string {
	if x != nil {
		return x.Klines
	}
	return nil
}

type FuturesPairsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs []*FuturesPair `protobuf:"bytes,1,rep,name=Pairs,proto3" json:"Pairs,omitempty"`
}

func (x *FuturesPairsResponse) Reset() {
	*x = FuturesPairsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ds_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuturesPairsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuturesPairsResponse) ProtoMessage() {}

func (x *FuturesPairsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ds_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuturesPairsResponse.ProtoReflect.Descriptor instead.
func (*FuturesPairsResponse) Descriptor() ([]byte, []int) {
	return file_ds_api_proto_rawDescGZIP(), []int{4}
}

func (x *FuturesPairsResponse) GetPairs() []*FuturesPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type FuturesPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol    string  `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	BaseAsset string  `protobuf:"bytes,2,opt,name=BaseAsset,proto3" json:"BaseAsset,omitempty"`
	PriceStep float64 `protobuf:"fixed64,3,opt,name=PriceStep,proto3" json:"PriceStep,omitempty"`
	LotStep   float64 `protobuf:"fixed64,4,opt,name=LotStep,proto3" json:"LotStep,omitempty"`
}

func (x *FuturesPair) Reset() {
	*x = FuturesPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ds_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuturesPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuturesPair) ProtoMessage() {}

func (x *FuturesPair) ProtoReflect() protoreflect.Message {
	mi := &file_ds_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuturesPair.ProtoReflect.Descriptor instead.
func (*FuturesPair) Descriptor() ([]byte, []int) {
	return file_ds_api_proto_rawDescGZIP(), []int{5}
}

func (x *FuturesPair) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FuturesPair) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *FuturesPair) GetPriceStep() float64 {
	if x != nil {
		return x.PriceStep
	}
	return 0
}

func (x *FuturesPair) GetLotStep() float64 {
	if x != nil {
		return x.LotStep
	}
	return 0
}

type SocketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol      string `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Interval    string `protobuf:"bytes,2,opt,name=Interval,proto3" json:"Interval,omitempty"`
	IsSubscribe bool   `protobuf:"varint,3,opt,name=IsSubscribe,proto3" json:"IsSubscribe,omitempty"`
}

func (x *SocketRequest) Reset() {
	*x = SocketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ds_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketRequest) ProtoMessage() {}

func (x *SocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ds_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketRequest.ProtoReflect.Descriptor instead.
func (*SocketRequest) Descriptor() ([]byte, []int) {
	return file_ds_api_proto_rawDescGZIP(), []int{6}
}

func (x *SocketRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SocketRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *SocketRequest) GetIsSubscribe() bool {
	if x != nil {
		return x.IsSubscribe
	}
	return false
}

type SocketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *SocketResponse) Reset() {
	*x = SocketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ds_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketResponse) ProtoMessage() {}

func (x *SocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ds_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketResponse.ProtoReflect.Descriptor instead.
func (*SocketResponse) Descriptor() ([]byte, []int) {
	return file_ds_api_proto_rawDescGZIP(), []int{7}
}

func (x *SocketResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_ds_api_proto protoreflect.FileDescriptor

var file_ds_api_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x06, 0x0a, 0x04, 0x76, 0x6f, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x0a, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x59, 0x0a, 0x0d,
	0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x28, 0x0a, 0x0e, 0x4b, 0x6c, 0x69, 0x6e, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4b, 0x6c, 0x69,
	0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x4b, 0x6c, 0x69, 0x6e, 0x65,
	0x73, 0x22, 0x3d, 0x0a, 0x14, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x50, 0x61, 0x69,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x75,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x50, 0x61, 0x69, 0x72, 0x73,
	0x22, 0x7b, 0x0a, 0x0b, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x65, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x42, 0x61, 0x73, 0x65,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x63, 0x65, 0x53, 0x74,
	0x65, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x50, 0x72, 0x69, 0x63, 0x65, 0x53,
	0x74, 0x65, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f, 0x74, 0x53, 0x74, 0x65, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x4c, 0x6f, 0x74, 0x53, 0x74, 0x65, 0x70, 0x22, 0x65, 0x0a,
	0x0d, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x73, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x49, 0x73, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x22, 0x2c, 0x0a, 0x0e, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xde, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x12,
	0x25, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x08, 0x2e, 0x70, 0x62, 0x2e,
	0x76, 0x6f, 0x69, 0x64, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4b, 0x6c, 0x69,
	0x6e, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x6c, 0x69, 0x6e,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x73, 0x12,
	0x08, 0x2e, 0x70, 0x62, 0x2e, 0x76, 0x6f, 0x69, 0x64, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x46,
	0x75, 0x74, 0x75, 0x72, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x53,
	0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x48, 0x65, 0x6c, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ds_api_proto_rawDescOnce sync.Once
	file_ds_api_proto_rawDescData = file_ds_api_proto_rawDesc
)

func file_ds_api_proto_rawDescGZIP() []byte {
	file_ds_api_proto_rawDescOnce.Do(func() {
		file_ds_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_ds_api_proto_rawDescData)
	})
	return file_ds_api_proto_rawDescData
}

var file_ds_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ds_api_proto_goTypes = []interface{}{
	(*Void)(nil),                 // 0: pb.void
	(*ServerTime)(nil),           // 1: pb.ServerTime
	(*KlinesRequest)(nil),        // 2: pb.KlinesRequest
	(*KlinesResponse)(nil),       // 3: pb.KlinesResponse
	(*FuturesPairsResponse)(nil), // 4: pb.FuturesPairsResponse
	(*FuturesPair)(nil),          // 5: pb.FuturesPair
	(*SocketRequest)(nil),        // 6: pb.SocketRequest
	(*SocketResponse)(nil),       // 7: pb.SocketResponse
}
var file_ds_api_proto_depIdxs = []int32{
	5, // 0: pb.FuturesPairsResponse.Pairs:type_name -> pb.FuturesPair
	0, // 1: pb.DataServ.GetTime:input_type -> pb.void
	2, // 2: pb.DataServ.GetKlines:input_type -> pb.KlinesRequest
	0, // 3: pb.DataServ.GetFuturesPairs:input_type -> pb.void
	6, // 4: pb.DataServ.GetSocketData:input_type -> pb.SocketRequest
	1, // 5: pb.DataServ.GetTime:output_type -> pb.ServerTime
	3, // 6: pb.DataServ.GetKlines:output_type -> pb.KlinesResponse
	4, // 7: pb.DataServ.GetFuturesPairs:output_type -> pb.FuturesPairsResponse
	7, // 8: pb.DataServ.GetSocketData:output_type -> pb.SocketResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ds_api_proto_init() }
func file_ds_api_proto_init() {
	if File_ds_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ds_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ds_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ds_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KlinesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ds_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KlinesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ds_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuturesPairsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ds_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuturesPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ds_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ds_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ds_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ds_api_proto_goTypes,
		DependencyIndexes: file_ds_api_proto_depIdxs,
		MessageInfos:      file_ds_api_proto_msgTypes,
	}.Build()
	File_ds_api_proto = out.File
	file_ds_api_proto_rawDesc = nil
	file_ds_api_proto_goTypes = nil
	file_ds_api_proto_depIdxs = nil
}
